Repository IT-Cotato/9th-Growing-Pain-BE, pull requests merged in 2024-06, with the labels that each got.

#1 Feat: member 기본 erd 설정
  src/main/java/cotato/growingpain/common/domain/BaseTimeEntity.java
  src/main/java/cotato/growingpain/member/domain/Member.java
  src/main/java/cotato/growingpain/member/domain/MemberBelong.java
  src/main/java/cotato/growingpain/member/domain/MemberJob.java
Labels: ✨ Feature, 🦦yunhacandy

#4 ✨ Feature: #1 setting domain entity
  src/main/java/cotato/growingpain/comment/domain/entity/Comment.java
  src/main/java/cotato/growingpain/comment/domain/entity/CommentLike.java
  src/main/java/cotato/growingpain/log/domain/ActivityType.java
  src/main/java/cotato/growingpain/log/domain/ApplicationType.java
  src/main/java/cotato/growingpain/log/domain/Result.java
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/log/domain/entity/MemberJobApplication.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/domain/entity/PostLike.java
  src/main/java/cotato/growingpain/post/domain/entity/PostSave.java
  src/main/java/cotato/growingpain/replycomment/domain/entity/ReplyComment.java
  src/main/java/cotato/growingpain/replycomment/domain/entity/ReplyCommentLike.java
Labels: ⚙ Setting, ✨ Feature, ☁️ nar0ng

#6 🔨 Refactor: #1 member, community 관련 erd 수정
  src/main/java/cotato/growingpain/member/domain/MemberBelong.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
Labels: ⚙ Setting, 🔨 Refactor, 🦦yunhacandy

#13 🔨 Refactor : #2 refactor update activitylog userjobapplication table
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/log/domain/entity/MemberJobApplication.java
Labels: ⚙ Setting, 🔨 Refactor, ☁️ nar0ng

#10 ✨ Feature: #2 Build CI/CD
  .github/workflows/deploy.yaml
  appspec.yml
  build.gradle
  scripts/deploy.sh
Labels: ✨ Feature, 🌏 Deploy, 🦦yunhacandy

#16 Fix: CI/CD 관련 누락 파일 다시 입력
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
Labels: 🐞 BugFix, ⚙ Setting, 🌏 Deploy, 🦦yunhacandy

#22 Fix: MySQL DB 연결 에러 해결
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/log/domain/entity/MemberJobApplication.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
Labels: 🐞 BugFix, 🔨 Refactor, ☁️ nar0ng, 🦦yunhacandy

#24 Fix: Spring boot test 경로 수정
  src/test/java/cotato/growingpain/GrowingPainApplicationTests.java
Labels: 🐞 BugFix, 🦦yunhacandy
