Repository IT-Cotato/9th-Growing-Pain-BE, pull requests merged in 2024-07, with the labels that each got.

#25 Fix: CI/CD 관련 오류 해결
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🦦yunhacandy

#26 Fix: CI/CD 관련 오류 해결
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🦦yunhacandy

#27 Fix: CI/CD 관련 오류 해결
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🦦yunhacandy

#31 Feat: 회원가입 API 구현
  build.gradle
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/dto/request/JoinRequest.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/auth/service/ValidateService.java
  src/main/java/cotato/growingpain/common/exception/AppException.java
  src/main/java/cotato/growingpain/common/exception/AppExceptionHandler.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/config/JpaConfig.java
  src/main/java/cotato/growingpain/config/SecurityConfig.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/member/repository/MemberRepository.java
Labels: ✨ Feature, 🦦yunhacandy

#35 Feat: swagger 기능 구현
  build.gradle
  src/main/java/cotato/growingpain/config/SecurityConfig.java
Labels: ⚙ Setting, ✨ Feature, 🦦yunhacandy

#36 ✨ Feature: #4 redis test
  build.gradle
  src/main/java/cotato/growingpain/config/RedisConfig.java
  src/main/java/cotato/growingpain/log/domain/ApplicationType.java
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/test/Person.java
  src/main/java/cotato/growingpain/test/PersonRepository.java
  src/main/resources/application.yml
  src/test/java/cotato/growingpain/RedisRepositoryTest.java
Labels: ⚙ Setting, ☁️ nar0ng

#37 fix: delete Redis test
  src/test/java/cotato/growingpain/RedisRepositoryTest.java
Labels: 🐞 BugFix, ☁️ nar0ng

#39 🔨 Refactor: #5 fix table structure
  src/main/java/cotato/growingpain/config/JpaConfig.java
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/log/domain/entity/ApplicationDetail.java
  src/main/java/cotato/growingpain/log/domain/entity/JobApplication.java
  src/main/java/cotato/growingpain/log/domain/entity/JobPost.java
Labels: 🔨 Refactor, ☁️ nar0ng

#41 🔨 fix: member의 memberJobApplication 이름 변경 반영
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
Labels: 🐞 BugFix, ☁️ nar0ng

#33 Feat: Implement login using jwt
  src/main/java/cotato/growingpain/auth/AuthDetails.java
  src/main/java/cotato/growingpain/auth/AuthDetailsService.java
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/config/RedisConfig.java
  src/main/java/cotato/growingpain/config/SecurityConfig.java
  src/main/java/cotato/growingpain/member/domain/MemberRole.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/security/RefreshTokenRepository.java
  src/main/java/cotato/growingpain/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/growingpain/security/jwt/RefreshTokenEntity.java
  src/main/java/cotato/growingpain/security/jwt/Token.java
  src/main/java/cotato/growingpain/security/jwt/dto/request/ReissueRequest.java
  src/main/java/cotato/growingpain/security/jwt/dto/response/ReissueResponse.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthorizationFilter.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🦦yunhacandy

#44 🐛 Bug: #8 create bean error
  src/main/java/cotato/growingpain/config/JpaConfig.java
  src/main/java/cotato/growingpain/log/domain/service/JobApplicationService.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#45 Feat: 리이슈, 로그아웃, 블랙리스트 API 구현
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/domain/BlackList.java
  src/main/java/cotato/growingpain/auth/dto/request/LogoutRequest.java
  src/main/java/cotato/growingpain/auth/repository/BlackListRepository.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/config/RedisConfig.java
  src/main/java/cotato/growingpain/config/SecurityConfig.java
  src/main/java/cotato/growingpain/security/RefreshTokenRepository.java
  src/main/java/cotato/growingpain/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/growingpain/security/jwt/RefreshTokenEntity.java
  src/main/java/cotato/growingpain/security/jwt/dto/response/ReissueResponse.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthorizationFilter.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#47 Feat: 비밀번호 찾을 시 임시 비밀번호 발급되는 기능 구현
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/dto/request/ChangePasswordRequest.java
  src/main/java/cotato/growingpain/auth/dto/response/ChangePasswordResponse.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/auth/service/ValidateService.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
Labels: ✨ Feature, 🦦yunhacandy

#49 Feat: 응답 형식 추가 및 리팩토링
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/common/Response.java
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#51 Feat: 커뮤니티 중 게시글 관련 기능 구현
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/dto/request/PostRegisterRequest.java
  src/main/java/cotato/growingpain/post/repository/PostRepository.java
  src/main/java/cotato/growingpain/post/service/PostService.java
  src/main/java/cotato/growingpain/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/cotato/growingpain/security/jwt/filter/JwtAuthorizationFilter.java
Labels: ✨ Feature, 🦦yunhacandy

#53 Feat: 커뮤니티 관련 기능 중 댓글 관련 기능 구현
  src/main/java/cotato/growingpain/comment/controller/CommentController.java
  src/main/java/cotato/growingpain/comment/domain/entity/Comment.java
  src/main/java/cotato/growingpain/comment/dto/request/CommentRegisterRequest.java
  src/main/java/cotato/growingpain/comment/repository/CommentRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/config/SecurityConfig.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
Labels: ✨ Feature, 🦦yunhacandy

#55 Refactor: 팀원모집 카테고리 하위 카테고리 선택 기능 추가
  src/main/java/cotato/growingpain/post/PostCategory.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/repository/PostRepository.java
  src/main/java/cotato/growingpain/post/service/PostService.java
Labels: 🔨 Refactor, 🦦yunhacandy

#57 Refactor: AuthController에 swagger 관련 어노테이션 추가
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
Labels: 🔨 Refactor, 🦦yunhacandy

#58 Refactor:modify controller for swagger
  src/main/java/cotato/growingpain/comment/controller/CommentController.java
  src/main/java/cotato/growingpain/comment/domain/entity/Comment.java
  src/main/java/cotato/growingpain/comment/dto/response/CommentListResponse.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/dto/response/PostListResponse.java
  src/main/java/cotato/growingpain/post/service/PostService.java
Labels: 🔨 Refactor, 🦦yunhacandy

#62 Feat: 좋아요 등록 및 취소 기능 구현
  src/main/java/cotato/growingpain/comment/controller/CommentLikeController.java
  src/main/java/cotato/growingpain/comment/domain/entity/Comment.java
  src/main/java/cotato/growingpain/comment/domain/entity/CommentLike.java
  src/main/java/cotato/growingpain/comment/repository/CommentLikeRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentLikeService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/post/controller/PostLikeController.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/domain/entity/PostLike.java
  src/main/java/cotato/growingpain/post/repository/PostLikeRepository.java
  src/main/java/cotato/growingpain/post/service/PostLikeService.java
  src/main/java/cotato/growingpain/replycomment/controller/ReplyCommentLikeController.java
  src/main/java/cotato/growingpain/replycomment/domain/entity/ReplyComment.java
  src/main/java/cotato/growingpain/replycomment/domain/entity/ReplyCommentLike.java
  src/main/java/cotato/growingpain/replycomment/repository/ReplyCommentLikeRepository.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentLikeService.java
Labels: ✨ Feature, 🦦yunhacandy

#65 🔨 Refactor: refactor job application
  src/main/java/cotato/growingpain/log/domain/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/domain/dto/JobApplicationRetrieveDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobPostRequestDTO.java
  src/main/java/cotato/growingpain/log/domain/service/JobService.java
Labels: 📃 Docs, 🔨 Refactor, ☁️ nar0ng

#66 ✨ Feat: 본인이 작성한 콘텐츠는 좋아요 못하게 하는 기능 구현
  src/main/java/cotato/growingpain/comment/domain/entity/Comment.java
  src/main/java/cotato/growingpain/comment/service/CommentLikeService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/service/PostLikeService.java
  src/main/java/cotato/growingpain/replycomment/domain/entity/ReplyComment.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentLikeService.java
Labels: ✨ Feature, 🦦yunhacandy

#73 ✨ Feat: 게시글 수정 기능 구현
  src/main/java/cotato/growingpain/common/domain/BaseTimeEntity.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/domain/entity/Post.java
  src/main/java/cotato/growingpain/post/dto/request/PostRequest.java
  src/main/java/cotato/growingpain/post/service/PostService.java
Labels: ✨ Feature, 🦦yunhacandy

#75 🔨 Refactor: 커뮤니티 관련 기능 리팩토링
  src/main/java/cotato/growingpain/comment/controller/CommentController.java
  src/main/java/cotato/growingpain/comment/controller/CommentLikeController.java
  src/main/java/cotato/growingpain/comment/dto/response/CommentListResponse.java
  src/main/java/cotato/growingpain/comment/dto/response/CommentResponse.java
  src/main/java/cotato/growingpain/comment/repository/CommentRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentLikeService.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/controller/PostLikeController.java
  src/main/java/cotato/growingpain/post/controller/PostSaveController.java
  src/main/java/cotato/growingpain/post/service/PostLikeService.java
  src/main/java/cotato/growingpain/post/service/PostSaveService.java
  src/main/java/cotato/growingpain/post/service/PostService.java
  src/main/java/cotato/growingpain/replycomment/controller/ReplyCommentLikeController.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentLikeService.java
Labels: 🔨 Refactor, 🦦yunhacandy
