Repository IT-Cotato/9th-Growing-Pain-BE, pull requests merged in 2024-08, with the labels that each got.

#76 Refactor: 커뮤니티 기능 api path 수정
  src/main/java/cotato/growingpain/comment/controller/CommentController.java
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/replycomment/controller/ReplyCommentController.java
Labels: 🔨 Refactor, 🦦yunhacandy

#78 Feat: 사용자가 작성한 포스트내의 모든 댓글 목록 조회
  src/main/java/cotato/growingpain/comment/controller/CommentController.java
  src/main/java/cotato/growingpain/comment/dto/response/CommentResponse.java
  src/main/java/cotato/growingpain/comment/repository/CommentRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#79 Refactor: 프론트와의 소통을 위해 커뮤니티 기능 리팩토링
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/controller/PostSaveController.java
Labels: ⚙ Setting, 🔨 Refactor, 🦦yunhacandy

#80 ✨ Feat: 추가 정보 받는 기능 구현
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/dto/request/CompleteSignupRequest.java
  src/main/java/cotato/growingpain/auth/dto/request/LoginRequest.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#82 Feat: 로컬과 배포 환경에 따른 Swagger 설정
  src/main/java/cotato/growingpain/config/SwaggerConfig.java
Labels: ⚙ Setting, ✨ Feature, 🌏 Deploy, 🦦yunhacandy

#83 ✨ Feature: 지원현황 관련 API 구현
  src/main/java/cotato/growingpain/log/domain/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/domain/dto/ApplicationDetailRequestDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobApplicationRequestDTO.java
  src/main/java/cotato/growingpain/log/domain/entity/ApplicationDetail.java
  src/main/java/cotato/growingpain/log/domain/entity/JobApplication.java
  src/main/java/cotato/growingpain/log/domain/entity/JobPost.java
  src/main/java/cotato/growingpain/log/domain/service/JobService.java
Labels: ✨ Feature, ☁️ nar0ng

#86 ✨ Feature: #11 setting spring boot errorlog discord system
  build.gradle
  src/main/java/cotato/growingpain/test/TestController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: ⚙ Setting, ✨ Feature, 🌏 Deploy, ☁️ nar0ng

#89 ✨ Feature: #7 jobapplicaiton crud
  src/main/java/cotato/growingpain/log/domain/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/domain/dto/ApplicationDetailDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobApplicationListRetrieveDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobApplicationRetrieveDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobPostListRetrieveDTO.java
  src/main/java/cotato/growingpain/log/domain/dto/JobPostRetrieveDTO.java
  src/main/java/cotato/growingpain/log/domain/entity/JobPost.java
  src/main/java/cotato/growingpain/log/domain/repository/JobPostRepository.java
  src/main/java/cotato/growingpain/log/domain/service/JobService.java
  src/main/resources/application-local.yml
  src/main/resources/logback.xml
Labels: ✨ Feature, 🔨 Refactor, ☁️ nar0ng

#91 🔨 Fix: application.yml, application-dev.yml, applciation-local.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🐞 BugFix, 🌏 Deploy

#92 fix: logback-spring.xml -> logback.xml로 되돌림
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/logback.xml
Labels: 🐞 BugFix, 🌏 Deploy, ☁️ nar0ng

#93 fix: 원래 파일대로 되돌림
  src/main/resources/logback.xml
Labels: 🐞 BugFix, 🌏 Deploy, ☁️ nar0ng

#94 🔨 Fix :#12 server error
  src/main/resources/application-local.yml
  src/main/resources/logback-test.xml
  src/main/resources/logback.xml
Labels: 🐞 BugFix, 🌏 Deploy, ☁️ nar0ng

#95 Refactor: 확장성을 고려한 auth 관련 기능 리팩토링
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/security/oauth/AuthProvider.java
  src/main/resources/application-local.yml
Labels: 🔨 Refactor, 🦦yunhacandy

#97 🔨 chore: logback-spring.xml renamed
  src/main/java/cotato/growingpain/log/domain/controller/JobPostController.java
  src/main/resources/application-dev.yml
  src/main/resources/logback-spring.xml
Labels: 🐞 BugFix, 🌏 Deploy, ☁️ nar0ng

#100 Bug/#12 server error
  src/main/java/cotato/growingpain/config/CorsConfig.java
Labels: 🐞 BugFix, 🌏 Deploy, ☁️ nar0ng

#101 Feat: 마이페이지 중 프로필 공개 여부 관한 기능 구현
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/member/controller/MemberController.java
  src/main/java/cotato/growingpain/member/domain/MemberProfileShowing.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/member/dto/request/AdditionalInfoRequest.java
  src/main/java/cotato/growingpain/member/dto/request/UpdateMemberProfileShowingRequest.java
  src/main/java/cotato/growingpain/member/dto/response/MemberInfoResponse.java
  src/main/java/cotato/growingpain/member/service/MemberService.java
Labels: ✨ Feature, 🦦yunhacandy

#104 ✨ Feature: #13 feature activity log crud
  src/main/java/cotato/growingpain/log/ActivityCategory.java
  src/main/java/cotato/growingpain/log/ApplicationType.java
  src/main/java/cotato/growingpain/log/Result.java
  src/main/java/cotato/growingpain/log/controller/ActivityLogController.java
  src/main/java/cotato/growingpain/log/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/domain/entity/ActivityLog.java
  src/main/java/cotato/growingpain/log/domain/entity/ApplicationDetail.java
  src/main/java/cotato/growingpain/log/domain/entity/JobApplication.java
  src/main/java/cotato/growingpain/log/domain/entity/JobPost.java
  src/main/java/cotato/growingpain/log/domain/service/JobApplicationService.java
  src/main/java/cotato/growingpain/log/dto/ActivityLogDTO.java
  src/main/java/cotato/growingpain/log/dto/ApplicationDetailDTO.java
  src/main/java/cotato/growingpain/log/dto/request/ActivityLogRequestDTO.java
  src/main/java/cotato/growingpain/log/dto/request/ApplicationDetailRequestDTO.java
  src/main/java/cotato/growingpain/log/dto/request/JobApplicationRequestDTO.java
  src/main/java/cotato/growingpain/log/dto/request/JobPostRequestDTO.java
  src/main/java/cotato/growingpain/log/dto/request/JobPostRetrieveDTO.java
  src/main/java/cotato/growingpain/log/dto/retrieve/JobApplicationListRetrieveDTO.java
  src/main/java/cotato/growingpain/log/dto/retrieve/JobApplicationRetrieveDTO.java
  src/main/java/cotato/growingpain/log/dto/retrieve/JobPostListRetrieveDTO.java
  src/main/java/cotato/growingpain/log/repository/ActivityLogRepository.java
  src/main/java/cotato/growingpain/log/repository/ApplicationDetailRepository.java
  src/main/java/cotato/growingpain/log/repository/JobApplicationRepository.java
  src/main/java/cotato/growingpain/log/repository/JobPostRepository.java
  src/main/java/cotato/growingpain/log/service/ActivityLogService.java
  src/main/java/cotato/growingpain/log/service/JobService.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
Labels: ✨ Feature, ☁️ nar0ng

#105 Refactor: 이메일 및 닉네임 중복 확인 메소드 추가
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/dto/request/DuplicateCheckRequest.java
  src/main/java/cotato/growingpain/auth/dto/response/DuplicateCheckResponse.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
  src/main/java/cotato/growingpain/auth/service/ValidateService.java
  src/main/java/cotato/growingpain/common/exception/ErrorCode.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#107 refactor: 게시글 목록 반환 기능 수정
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/controller/PostSaveController.java
  src/main/java/cotato/growingpain/post/dto/response/PostListResponse.java
  src/main/java/cotato/growingpain/post/dto/response/PostResponse.java
  src/main/java/cotato/growingpain/post/repository/PostRepository.java
  src/main/java/cotato/growingpain/post/service/PostService.java
Labels: 🐞 BugFix, 🔨 Refactor, 🦦yunhacandy

#108 Refactor: 게시글 목록 반환 응답 수정
  src/main/java/cotato/growingpain/post/dto/response/PostResponse.java
Labels: 🔨 Refactor, 🦦yunhacandy

#110 🔨 refact: 리스트 조회 시 id 값 추가로 반환
  src/main/java/cotato/growingpain/log/dto/request/ActivityLogRequestDTO.java
  src/main/java/cotato/growingpain/log/dto/retrieve/JobPostListRetrieveDTO.java
Labels: 🔨 Refactor, ☁️ nar0ng

#112 feat: 로그인 시 회원정보 반환되게 응답 추가
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
  src/main/java/cotato/growingpain/auth/dto/LoginResponse.java
  src/main/java/cotato/growingpain/auth/service/AuthService.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#113 Fix: time zone 한국시각에 맞춰서 에러 해결
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🐞 BugFix, ⚙ Setting, 🦦yunhacandy

#114 Fix: application 코드에도 time zone 문제 해결
  src/main/java/cotato/growingpain/GrowingPainApplication.java
Labels: 🐞 BugFix, ⚙ Setting, 🦦yunhacandy

#116 Refactor/#29 modify post related features
  src/main/java/cotato/growingpain/comment/controller/CommentLikeController.java
  src/main/java/cotato/growingpain/comment/repository/CommentLikeRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentLikeService.java
  src/main/java/cotato/growingpain/post/controller/PostLikeController.java
  src/main/java/cotato/growingpain/post/repository/PostLikeRepository.java
  src/main/java/cotato/growingpain/post/service/PostLikeService.java
  src/main/java/cotato/growingpain/replycomment/controller/ReplyCommentLikeController.java
  src/main/java/cotato/growingpain/replycomment/repository/ReplyCommentLikeRepository.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentLikeService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#118 REFACTOR: 커뮤니티 관련 기능 수정
  src/main/java/cotato/growingpain/comment/dto/response/CommentResponse.java
  src/main/java/cotato/growingpain/comment/repository/CommentRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/post/dto/response/PostResponse.java
  src/main/java/cotato/growingpain/post/service/PostSaveService.java
  src/main/java/cotato/growingpain/replycomment/controller/ReplyCommentController.java
  src/main/java/cotato/growingpain/replycomment/dto/response/ReplyCommentListResponse.java
  src/main/java/cotato/growingpain/replycomment/dto/response/ReplyCommentResponse.java
  src/main/java/cotato/growingpain/replycomment/repository/ReplyCommentRepository.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentService.java
Labels: 🐞 BugFix, 🔨 Refactor, 🦦yunhacandy

#119 Fix: isDeleted가 true인 게시글, 댓글, 답글은 목록으로 반환되지 않게 수정
  src/main/java/cotato/growingpain/comment/repository/CommentRepository.java
  src/main/java/cotato/growingpain/comment/service/CommentService.java
  src/main/java/cotato/growingpain/post/repository/PostRepository.java
  src/main/java/cotato/growingpain/post/service/PostService.java
  src/main/java/cotato/growingpain/replycomment/repository/ReplyCommentRepository.java
  src/main/java/cotato/growingpain/replycomment/service/ReplyCommentService.java
Labels: 🐞 BugFix, 🔨 Refactor, 🦦yunhacandy

#121 Refactor: 이메일 및 닉네임 중복 request 형식 수정
  src/main/java/cotato/growingpain/auth/controller/AuthController.java
Labels: 🔨 Refactor, 🦦yunhacandy

#122 Fix: 모든 카테고리에 대한 post 조회 기능 에러 수정
  src/main/java/cotato/growingpain/post/controller/PostController.java
  src/main/java/cotato/growingpain/post/repository/PostRepository.java
  src/main/java/cotato/growingpain/post/service/PostService.java
Labels: 🐞 BugFix, 🔨 Refactor, 🦦yunhacandy

#123 Refactor: 마이페이지 관련 기능 수정
  src/main/java/cotato/growingpain/member/controller/MemberController.java
  src/main/java/cotato/growingpain/member/domain/entity/Member.java
  src/main/java/cotato/growingpain/member/dto/request/AdditionalInfoRequest.java
  src/main/java/cotato/growingpain/member/dto/request/UpdateDefaultInfoRequest.java
  src/main/java/cotato/growingpain/member/dto/response/MemberInfoResponse.java
  src/main/java/cotato/growingpain/member/service/MemberService.java
Labels: 🔨 Refactor, 🦦yunhacandy

#126 🔨 Fix: 지원현황 상세 조회 시 출력값 변경
  src/main/java/cotato/growingpain/log/dto/retrieve/JobApplicationRetrieveDTO.java
Labels: 🐞 BugFix, ☁️ nar0ng

#128 Feat: 일정 기간이 남은 지원 현황을 조회하여 반환하는 기능 구현
  src/main/java/cotato/growingpain/log/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/dto/response/JobApplicationListResponse.java
  src/main/java/cotato/growingpain/log/dto/response/JobApplicationResponse.java
  src/main/java/cotato/growingpain/log/repository/JobApplicationRepository.java
  src/main/java/cotato/growingpain/log/service/JobService.java
Labels: ✨ Feature, 🔨 Refactor, 🦦yunhacandy

#130 Refactor:
  src/main/java/cotato/growingpain/log/controller/JobPostController.java
  src/main/java/cotato/growingpain/log/service/JobService.java
Labels: 🔨 Refactor, 🦦yunhacandy
